# Generated by Django 3.1.6 on 2021-02-19 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signUp', '0004_auto_20210219_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_desc', models.CharField(max_length=1000)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signUp.users')),
            ],
        ),
    ]
