# Generated by Django 3.1.6 on 2021-02-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0002_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
